### PR TITLE
Added support for disabling FreHD

### PR DESCRIPTION
**Pull request by pski**
This allows use of TRS-IO with other devices that include HD functions, ie. M3SE, Lo-tech IDE, stand alone SD card FreHD and real OEM RS hard drives.

### CODE REVIEW

**Comment by apuder** [comment]
I think it is a good idea to have a feature that allows to disable FreHD. Perhaps a cleaner solution would be to add a switch to the PCB that would make it easy to enable and disable (unfortunately this cannot be done in software due to the BUS_WAIT signal that the GAL generates). What do you think, @jaquinn ?

**Comment by apuder** [comment]
@jaquinn how about using an unused input pin of the GAL to either assert to high or low via a push button? Then in the GAL equations we can disable the FreHD ports?

**Comment by jaquinn** [comment]
I think that would definitely work.  Pins 1 and 11 look to be free at the moment.  It should be easy enough to pull one of these up to VCC by default and to GND with a jumper to disable the FREHD port decoding and potentially the generation of /WAIT.  I haven't checked the code... are the network functions fast enough that /WAIT is not required?

**Comment by apuder** [comment]
The GAL will assert the WAIT signal whenever the 0xCx ports are detected. That is why a pure software solution to disable FreHD is not possible. Using a jumper is an excellent idea! @jaquinn since you are our resident KiCAD expert, would you mind updating the schematics and PCB design? I can then update the GAL equations accordingly.

**Comment by pski** [comment]
The jumper is a great idea.

**Comment by jaquinn** [comment]
No problem.  I am traveling early this week so I will sort it when I get back home, likely while you guys are enjoying Thanksgiving dinner.  In the mean-time, can you "field test" the modification by adding a pull-up resistor (any value between 4K7 and 10K would be fine) between Pin 1 of the GAL and 5v.  This would pull GAL Pin 1 to "true" and would be the default configuration where FreHD should be enabled.  Test the updated equations with that to confirm they work.   Then with the resistor still in place, use a piece of wire to connect GAL Pin 1 to GND.  This will pull Pin 1 to "false" and your equations should disable FreHD port detection.

**Comment by apuder** [comment]
Thanks, @jaquinn. Please do a PR whenever you have time. @pski do you want to make that modification and test it? I can send you updated GAL equations. I'm currently traveling and can't do tests on the hardware.

**Comment by pski** [comment]
Sure, send me the update GAL code and I’ll test it.

**Comment by apuder** [comment]
Closing this PR and waiting for @jaquinn to do his PR.

**Pull request closed without merging**
